### ISSUE TITLE
TatukGIS webtile

### ISSUE THREAD

**Issue by dgslos** [earthcape/public#11]
I would add this as standard to the map projects. No need for the ttkwp file which is not present after installation but can be downloaded from a blog on takugis) for the openstreetmaps, which is standard in the 'Map project' navigation i would go for this webservice approach. I found it to be faster and no need for the ttkwp file. 

Source of the code: https://www.tatukgis.com/Support/QA/Question.aspx?itemid=84

```
[TatukGIS Layer1]
Active=YES
Visible=YES
Caption=TatukGIS OpenStreetMaps Tiles (Test)
CS.EPSG=3785
Name=tatukgis_osm
Path=TatukGIS OpenStreetMaps Tiles (Test)\\n[TatukGIS Layer]\\nStorage=WEBTILES\\nType=TMS\\nname=tatukgis_osm\\nCaption=TatukGIS OpenStreetMaps Tiles (Test)\\nUrl1=http://test1.tileservers.tatukgis.com/osm/\\nUrl2=http://test2.tileservers.tatukgis.com/osm/\\nUrl3=http://test3.tileservers.tatukgis.com/osm/\\nUrl4=http://test4.tileservers.tatukgis.com/osm/\\nFormat=png\\nCopyright=(c) OpenStreetMap contributors, CC-BY-SA.\\n.ttkwp

```

**Comment by emeyke** [comment]
Good idea!

Will be added to next update.
