### ISSUE TITLE
MYSQL compability of earthcape for sha2 with MYSQL 8

### ISSUE THREAD

**Issue by dgslos** [earthcape/public#13]
MYSQL compability with sha2 in MYSQL 8

**Comment by apobekiaris** [comment]
Hello, 

EarthCape uses MySql.Data connector to interact with MySQL databases which does not support this type of Authentication, if a newer version of the connector.offers support, will upgrade. However at the moment please use the legacy authentication method

**Comment by emeyke** [comment]
If this is an option for your setup, you can also consider this:
https://medium.com/@crmcmullen/how-to-run-mysql-8-0-with-native-password-authentication-502de5bac661

**Comment by dgslos** [comment]
Thanks for the link BUT as you can read in the text: "You can modify your applications to just use the newer (**and better performing**) caching_sha2_password method". Check also the answer here: https://dba.stackexchange.com/questions/209514/what-is-mysql-native-password. Basically, sha2 should be more secure. I got mysql 8 to work, but compatibility with more secure options is always better. :)

**Comment by emeyke** [comment]
That is correct. Although in this case we are dependent on modifications in MySql.Data. Hopefully it will not be long till it is implemented.

Thanks again for testing and spotting the problem.

Cheers,
Evgeniy
