### ISSUE TITLE
GIS (mapping data) issue

### ISSUE THREAD

**Issue by dgslos** [earthcape/public#24]
At the moment, data can be plotted on the map but this doesn't work properly. GPS coordinates entered in the format 50,979927; 3,778513 are plotted in the sea. This has probably something to do with the projection systems. Changing this in the map layers doesn't seem to give the wanted result. Also when localities are created in the gis editor of the software and then exported to some gis interpreted (for example google maps), the data is plotted on wrong locations. Again, probably the projection system. This should be resolved.

![image](https://user-images.githubusercontent.com/65173064/81574319-f0f9a180-93a5-11ea-9583-819cde67f652.png)

![image](https://user-images.githubusercontent.com/65173064/81574361-fd7dfa00-93a5-11ea-904b-042eb9db2813.png)

**Comment by emeyke** [comment]
Does it help to set EPSG to 4326 for the plotted record?

**Comment by dgslos** [comment]
[Media1.zip](https://github.com/earthcape/public/files/4615222/Media1.zip)

**Comment by emeyke** [comment]
Coudl you check how your geo fields look like for the data you are rtying to plot?
![image](https://user-images.githubusercontent.com/234025/81689288-cf122480-9462-11ea-8440-7fd8ecc8045c.png)

**Comment by emeyke** [comment]
Problem reproduced. WKT created automatically for values entered in Latitude and Longitude fields ends up having "," instead of "." depending on system settings.
Fixed in next update
